name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main   # deploy only when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build the JAR
      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      # 4️⃣ Copy the JAR to EC2
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/simpleAwsProject-1.0-SNAPSHOT.jar"
          target: "/home/ec2-user/"

      # 5️⃣ Restart systemd service on EC2
      - name: Restart Spring Boot systemd service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart simpleaws
            sudo systemctl status simpleaws --no-pager
