name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Copy JAR to EC2
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} target/simpleAwsProject-1.0-SNAPSHOT.jar \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Deploy on EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          SERVICE_FILE=/etc/systemd/system/simpleaws.service
          JAR_PATH=/home/ec2-user/simpleAwsProject-1.0-SNAPSHOT.jar